### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by bloodfued12** [bloodfued12/prework-study-guide-bootcamp#1]
# HTML 

## User story
As a boot camp student 
When given a prework study guide, I would like to be able to easily identify and find work that has been correctly sorted with a table of contents.

## Acceptance criteria
Given a prework study guide
When I visit the site in the browser,
Then I see several boxes titled with their appropriate titles, HTML, CSS, Javascript, etc.; this must also contain suitably related notes appropriate to the content.

**Comment by devashishroychowdhury** [comment]
### Kindly! provide me the link to website as then I will able to understand the issue.
